/*
 * Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com)
 *
 * WSO2 LLC. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package io.ballerina.mcp.core.generator;

import io.ballerina.mcp.core.model.EndpointInfo;
import io.ballerina.mcp.core.model.SpecInfo;

/**
 * Generates the content of {@code README.md} for a Ballerina MCP server project.
 */
public class ReadmeGenerator {

    private static final String NL = System.lineSeparator();

    /**
     * Generates the full content of {@code README.md}.
     *
     * @param spec the parsed spec information
     * @return the generated Markdown content as a string
     */
    public String generate(SpecInfo spec) {
        StringBuilder sb = new StringBuilder();

        sb.append("# ").append(spec.getTitle()).append(" - MCP Server").append(NL);
        sb.append(NL);
        sb.append("This project was auto-generated by the Ballerina MCP tool (`bal mcp`).").append(NL);
        sb.append("It provides a Ballerina MCP server that wraps the **")
                .append(spec.getTitle()).append("** API (v").append(spec.getVersion()).append(").").append(NL);
        sb.append(NL);

        sb.append("## Project Structure").append(NL);
        sb.append(NL);
        sb.append("```").append(NL);
        sb.append("├── Ballerina.toml    # Project configuration").append(NL);
        sb.append("├── main.bal          # MCP service with remote functions per API endpoint").append(NL);
        sb.append("├── types.bal         # Ballerina record types from API schemas").append(NL);
        sb.append("└── README.md         # This file").append(NL);
        sb.append("```").append(NL);
        sb.append(NL);

        sb.append("## Prerequisites").append(NL);
        sb.append(NL);
        sb.append("- [Ballerina Swan Lake](https://ballerina.io/downloads/) 2201.13.1 or later").append(NL);
        sb.append("- The upstream API must be reachable at: `").append(spec.getBaseUrl()).append("`").append(NL);
        sb.append(NL);

        sb.append("## Running the MCP Server").append(NL);
        sb.append(NL);
        sb.append("```bash").append(NL);
        sb.append("bal run").append(NL);
        sb.append("```").append(NL);
        sb.append(NL);
        sb.append("The MCP server will start on port **9090**.").append(NL);
        sb.append(NL);

        sb.append("## Available Tools").append(NL);
        sb.append(NL);
        sb.append("| Function | Method | Path | Description |").append(NL);
        sb.append("|---|---|---|---|").append(NL);
        for (EndpointInfo endpoint : spec.getEndpoints()) {
            sb.append("| `").append(endpoint.getToolName()).append("` | ")
                    .append(endpoint.getMethod().toUpperCase()).append(" | `")
                    .append(endpoint.getPath()).append("` | ")
                    .append(sanitizeDescription(endpoint.getDescription())).append(" |").append(NL);
        }
        sb.append(NL);

        sb.append("## Configuration").append(NL);
        sb.append(NL);
        sb.append("To change the upstream API base URL, update the `apiClient` declaration in `main.bal`:").append(NL);
        sb.append(NL);
        sb.append("```ballerina").append(NL);
        sb.append("http:Client apiClient = check new (\"<your-api-base-url>\");").append(NL);
        sb.append("```").append(NL);
        sb.append(NL);

        sb.append("---").append(NL);
        sb.append("*Generated by `bal mcp` — Ballerina OpenAPI-to-MCP Server Generation Tool*").append(NL);

        return sb.toString();
    }

    private String sanitizeDescription(String description) {
        if (description == null) {
            return "";
        }
        return description
                .replaceAll("\\r?\\n", " ")  // replace line breaks with space
                .replace("|", "\\|")          // escape pipe characters
                .trim();
    }
}
